## START SECTION TO BE CONFIGURED WITH YOUR OWN REPO PATH

[linters-settings.gci]
sections = ["standard", "default", "prefix(goadmin-backend)"]

[linters-settings.gofumpt]
extra-rules = true
module-path = "goadmin-backend"

[run]
timeout = "1m"

## END SECTION TO BE CONFIGURED WITH YOUR OWN REPO PATH

[service]
golangci-lint-version = "1.56"

[linters]
disable-all = true

enable = [
    "asasalint",
    "asciicheck",
    "bidichk",
    "bodyclose",
    "containedctx",
    "contextcheck",
    "cyclop",
    "decorder",
    "depguard",
    "dogsled",
    "dupl",
    "dupword",
    "durationcheck",
    "errcheck",
    "errchkjson",
    "errname",
    "errorlint",
    "execinquery",
    "exhaustive",
    "exportloopref",
    "forbidigo",
    "forcetypeassert",
    "gci",
    "ginkgolinter",
    "gocheckcompilerdirectives",
    "gochecknoglobals",
    "gochecknoinits",
    "gochecksumtype",
    "gocognit",
    "goconst",
    "gocritic",
    "gocyclo",
    "godox",
    "goerr113",
    "gofmt",
    "gofumpt",
    "goheader",
    "goimports",
    "gomnd",
    "gomoddirectives",
    "gomodguard",
    "goprintffuncname",
    "gosec",
    "gosimple",
    "gosmopolitan",
    "govet",
    "grouper",
    "importas",
    "ineffassign",
    "interfacebloat",
    "ireturn",
    "lll",
    "loggercheck",
    "maintidx",
    "makezero",
    "mirror",
    "misspell",
    "nakedret",
    "nestif",
    "nilerr",
    "nilnil",
    "nlreturn",
    "noctx",
    "nolintlint",
    "nonamedreturns",
    "nosprintfhostport",
    "paralleltest",
    "perfsprint",
    "prealloc",
    "predeclared",
    "promlinter",
    "protogetter",
    "reassign",
    "revive",
    "rowserrcheck",
    "sloglint",
    "spancheck",
    "sqlclosecheck",
    "staticcheck",
    "stylecheck",
    "tagalign",
    "tenv",
    "testableexamples",
    "testifylint",
    "thelper",
    "tparallel",
    "unconvert",
    "unparam",
    "unused",
    "usestdlibvars",
    "varnamelen",
    "wastedassign",
    "whitespace",
    "wrapcheck",
    "wsl",
    "zerologlint",

    # Disabled by your configuration linters:
    # deadcode [deprecated]: Finds unused code [fast: false, auto-fix: false]
    # exhaustivestruct [deprecated]: Checks if all struct's fields are initialized [fast: false, auto-fix: false]
    # exhaustruct: Checks if all structure fields are initialized [fast: false, auto-fix: false]
    # funlen: Tool for detection of long functions [fast: true, auto-fix: false]
    # godot: Check if comments end in a period [fast: true, auto-fix: true]
    # golint [deprecated]: Golint differs from gofmt. Gofmt reformats Go source code, whereas golint prints out style mistakes [fast: false, auto-fix: false]
    # ifshort [deprecated]: Checks that your code uses short syntax for if-statements whenever possible. [fast: true, auto-fix: false]
    # inamedparam: reports interfaces with unnamed method parameters [fast: true, auto-fix: false]
    # interfacer [deprecated]: Linter that suggests narrower interface types [fast: false, auto-fix: false]
    # maligned [deprecated]: Tool to detect Go structs that would take less memory if their fields were sorted [fast: false, auto-fix: false]
    # musttag: enforce field tags in (un)marshaled structs [fast: false, auto-fix: false]
    # nosnakecase [deprecated]: nosnakecase is a linter that detects snake case of variable naming and function name. [fast: true, auto-fix: false]
    # scopelint [deprecated]: Scopelint checks for unpinned variables in go programs [fast: true, auto-fix: false]
    # structcheck [deprecated]: Finds unused struct fields [fast: false, auto-fix: false]
    # tagliatelle: Checks the struct tags. [fast: true, auto-fix: false]
    # testpackage: linter that makes you use a separate _test package [fast: true, auto-fix: false]
    # varcheck [deprecated]: Finds unused global variables and constants [fast: false, auto-fix: false]]
]

[linters-settings.errcheck]
check-type-assertions = true
check-blank = true

[linters-settings.govet]
check-shadowing = true
enable-all = true
disable = ["fieldalignment"]

[linters-settings.revive]
confidence = 0.0

[linters-settings.prealloc]
simple = false
range-loops = true
for-loops = true

[linters-settings.gocritic]
enabled-tags = [
    "diagnostic",
    "experimental",
    "opinionated",
    "performance",
    "style",
]
disabled-checks = ["whyNoLint", "unnamedResult"]

[linters-settings.errorlint]
errorf = true

[linters-settings.nolintlint]
require-explanation = true
require-specific = true

[linters-settings.tagalign]
align = false

[[linters-settings.depguard.rules.prevent_unmaintained_packages.deny]]
pkg = "io/ioutil"
desc = "replaced by io and os packages since Go 1.16: https://tip.golang.org/doc/go1.16#ioutil"

[[linters-settings.depguard.rules.main.deny]]
pkg = "github.com/sirupsen/logrus"
desc =  "please use log/slog from std lib"

[[linters-settings.depguard.rules.main.deny]]
pkg = "github.com/pkg/errors"
desc = "please use errors from std lib"

[[linters-settings.depguard.rules.main.deny]]
pkg = "gorm.io/gorm"
desc = "please use pgx and learn sql"

[[linters-settings.depguard.rules.test.deny]]
pkg = "github.com/stretchr/testify/assert"
desc =  "please use go table tests and simple ifs"

[[linters-settings.depguard.rules.test.deny]]
pkg = "github.com/stretchr/testify/require"
desc =  "please use go table tests and simple ifs"

[[linters-settings.depguard.rules.test.deny]]
pkg = "github.com/stretchr/testify/suite"
desc =  "please use go table tests and simple ifs"

[[issues.exclude-rules]]
path = '(.+)_test\.go'
linters = [
    "funlen",
    "goconst",
    "interfacer",
    "dupl",
    "lll",
    "goerr113",
    "varnamelen",
    "errcheck",
    "gocritic",
    "cyclop",
    "wrapcheck",
    "gocognit",
    "contextcheck",
    "nlreturn",
    "gochecknoglobals",
    "errorlint",
]

[[issues.exclude-rules]]
linters = ["lll"]
source = "^//go:generate "
