openapi: 3.0.3
info:
  title: GoAdmin
  version: 1.0.0
  description: This is the GoAdmin backend API spec
  contact:
    name: buildpeak
    email: buildpeak@gmail.com
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
      description: Check if the service is healthy
      operationId: health-check
  /auth/login:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      description: Sign a user in
      operationId: auth-login
  /auth/logout:
    post:
      summary: Logout user
      security:
        - jwtAuth: []
      responses:
        '204':
          description: User logged out successfully
      operationId: auth-logout
      description: Sign a new out
  /auth/signup:
    post:
      summary: Register new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
              required:
                - username
                - email
                - password
                - first_name
                - last_name
      responses:
        '201':
          description: User registered successfully
      operationId: auth-register
      description: Sign a user up
  /auth/signin-with-google:
    post:
      summary: Sign in with Google
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id_token:
                  type: string
              required:
                - id_token
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
      operationId: auth-signin-with-google
      description: Sign a user in with Google
servers:
  - url: 'http://localhost:3600'
    description: Dev
components:
  securitySchemes:
    jwtAuth:
      type: apiKey
      in: header
      name: Authorization
      description: JWT token in the format "Bearer <token>"
